### PR TITLE
Jdb status

### PR DESCRIPTION
**Pull request by joshdbarton**
```
git fetch --all
git checkout JDB_status
```
This PR adds a "store" view to the "my store" button.  It changes the models so you need to remigrate.
Add two users using the app to the db (this gives you usable users to add the sql queries below to)
 Once you've remigrated, add these queries to DB browser:

```
INSERT INTO website_paymentcategory VALUES (null,  null, 'Visa');
INSERT INTO website_paymentcategory VALUES (null, null, 'MasterCard');
INSERT INTO website_paymentcategory VALUES (null, null, 'AMEX');
INSERT INTO website_producttype VALUES (null, null, 'Home Goods');
INSERT INTO website_producttype VALUES (null, null, 'Pets');
INSERT INTO website_product VALUES (null, null, '', 'Poop-a-Rie', 12, "Make your poop not stink", 1, 0, "Nashville", 1, 2);
INSERT INTO website_product VALUES (null, null, '', 'Febreeze', 12, "Make your house not stink", 1, 0, "Nashville", 1, 2);
INSERT INTO website_product VALUES (null, null, '', 'Sandalwood Candle', 12, "Make your house like a delicious forest", 1, 0, "Knoxville", 1, 1);
INSERT INTO website_product VALUES (null, null, '', 'Puppies', 12, "Australian Shepherd babies", 6, 0, "Knoxville", 2, 2);
INSERT INTO website_product VALUES (null, null, '', 'Sugar Baby', 12, "Sweet Sugary Baby goodness", 5, 0, "Knoxville", 2, 1);
INSERT INTO website_product VALUES (null, null, '' , 'Hamster', 12, "Furry cute rodents", 1, 0, "Knoxville", 2, 1);
```
After the data is uploaded, use your users to see their stores.  put some items in your cart and see if the totals are updated on the store, and complete an order to see that they've been added to "number sold"

Danke für kaufen bei Bangazon.de

### CODE REVIEW

**Comment by rsbabcock** [comment]
I'm checking it and when I add a payment type to and click submit payment I get this error:

screen shot 2018-08-23 at 5 40 04 pm

**Comment by joshdbarton** [comment]
I'm getting the same error now...checking what's wrong.  Don't worry about this until tomorrow!

**Comment by joshdbarton** [comment]
fixed!  Try it again tomorrow :-)

**Comment by rsbabcock** [comment]
👶 Ok!

**Comment by rsbabcock** [comment]
🐴 :shipit: stallion

**Pull request merged**
